sudo: required
services:
    - docker

before_install:
    - docker build -t joshuarippon/docker-ci-workflow -f Dockerfile.dev .

script:
    - docker run joshuarippon/docker-ci-workflow npm run test -- --coverage
